"""empty message

Revision ID: 34e3d8f8714c
Revises: 5921adcdc2e2
Create Date: 2025-04-22 08:32:16.457173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34e3d8f8714c'
down_revision = '5921adcdc2e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contato', schema=None) as batch_op:
        batch_op.drop_constraint('contato_email_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contato', schema=None) as batch_op:
        batch_op.create_unique_constraint('contato_email_key', ['email'])

    # ### end Alembic commands ###
