"""empty message

Revision ID: 592d88e5a9b4
Revises: 79792bba004d
Create Date: 2025-04-19 17:10:46.386097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '592d88e5a9b4'
down_revision = '79792bba004d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_comentarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('comentario', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contato', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_criacao', sa.DateTime(), nullable=True))
        batch_op.drop_column('data_envio')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('mensagem',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('mensagem',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('contato', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_envio', sa.DATETIME(), nullable=True))
        batch_op.drop_column('data_criacao')

    op.drop_table('post_comentarios')
    # ### end Alembic commands ###
