"""empty message

Revision ID: 79792bba004d
Revises: b6f70a12e4fe
Create Date: 2025-04-19 15:03:16.196922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79792bba004d'
down_revision = 'b6f70a12e4fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('mensagem', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contato', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_envio', sa.DateTime(), nullable=True))
        batch_op.drop_column('data_criacao')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contato', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_criacao', sa.DATETIME(), nullable=True))
        batch_op.drop_column('data_envio')

    op.drop_table('post')
    # ### end Alembic commands ###
